// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6z86rcxLFgG42bdbmj6JKwN-suk8r4cU',
    appId: '1:421425924868:web:2511dbbf13db072af5de51',
    messagingSenderId: '421425924868',
    projectId: 'ecomapp-cd132',
    authDomain: 'ecomapp-cd132.firebaseapp.com',
    storageBucket: 'ecomapp-cd132.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4YuMHA19jddbwU-9Xz1UI0aAUsHpvV6w',
    appId: '1:421425924868:android:5564ade48adcf3b8f5de51',
    messagingSenderId: '421425924868',
    projectId: 'ecomapp-cd132',
    storageBucket: 'ecomapp-cd132.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApFSINpgVPw8aJ0hjMK9xl2C6JDvIQipI',
    appId: '1:421425924868:ios:145600f580c30dd1f5de51',
    messagingSenderId: '421425924868',
    projectId: 'ecomapp-cd132',
    storageBucket: 'ecomapp-cd132.appspot.com',
    iosBundleId: 'com.example.database',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApFSINpgVPw8aJ0hjMK9xl2C6JDvIQipI',
    appId: '1:421425924868:ios:b6ac390245577570f5de51',
    messagingSenderId: '421425924868',
    projectId: 'ecomapp-cd132',
    storageBucket: 'ecomapp-cd132.appspot.com',
    iosBundleId: 'com.example.database.RunnerTests',
  );
}
